### PR TITLE
Make sure scripts moved to body have the right path

### LINKED ISSUE #297: Vulcanize is looking for scripts in the wrong place
I have a polymer element that includes a script, in my example it includes requirejs.

    <link rel="import" href="../polymer/polymer.html"/>
    <script src="../requirejs/require.js"></script>

With inlineScripts: true the vulcanize process now expects the require.js file relative to the location of the vulcanized file rather than the polymer file.

    ERROR finding resources/components/requirejs/require.js

I'm expecting the file to be somewhere else -> resources/external/bower/requirejs

This just showed up in 1.14.1.  We are looking into locking down our version to 1.14.0 to fix our build pipeline.

### PR DESCRIPTION
**Pull request by azakus**
Fixes #297

### CODE REVIEW

**Comment by azakus** [comment]
PTAL @garlicnation or @rictic

File: lib/vulcan.js [hunk 1]
```diff
@@ -244,13 +244,19 @@ Vulcan.prototype = {
           if (end === -1) {
```
Comment (garlicnation) [inline lib/vulcan.js]: I'd like to see this broken out into a function along these lines: https://gist.github.com/garlicnation/e6137465ecd2ba9aa022

**Comment by garlicnation** [comment]
LGTM
