### PR TITLE
Do not inline imports in templates

### LINKED ISSUE #353: Imports inside of templates are incorrectly processed
Given a construction of
```html
<template>
<link rel="import" href="foo.html">
</template>
```
Vulcanize will incorrectly inline or remove `foo.html`.

### PR DESCRIPTION
**Pull request by azakus**
Fixes #353

### CODE REVIEW

File: test/test.js [hunk 1]
```diff
@@ -1065,5 +1065,22 @@ suite('Vulcan', function() {
...
+          preds.hasTagName('link'),
+          preds.hasAttrValue('rel', 'import'),
+          preds.hasAttr('href')
+        );
+        if (err) {
+          return done(err);
+        }
+        assert(doc);
+        var imports = dom5.queryAll(doc, importMatcher);
+        assert.equal(imports.length, 1, 'import in template was inlined');
```
Comment (garlicnation) [inline test/test.js]: Add a negative assert for the absence of one of the elements from the inlined import.

**Comment by garlicnation** [comment]
LGTM with nit.

File: test/test.js (hunk 1 above)
Comment (azakus) [inline test/test.js]: Done!
