### PR TITLE
Fix inline script excludes

### LINKED ISSUE #158: [1.2.1] Using --inline-scripts and --exclude
I have excluded a path containing a js script, and combined with -inline-scripts.
The html file generated contains:  <script></script>, I think this is wrong because that line does nothing.
I expected vulcanize to do nothing with that line, it just removed the src attribute.

Thanks!

### PR DESCRIPTION
**Pull request by garlicnation**
Fixes #158

### CODE REVIEW

**Comment by azakus** [comment]
LGTM

File: lib/vulcan.js [hunk 1]
```diff
@@ -182,6 +185,9 @@ function inlineScripts(doc, href) {
     var src = dom5.getAttribute(script, 'src');
     var uri = URL.resolve(href, src);
     // let the loader handle the requests
+    if (isEcludedHref(src)) {
```
Comment (azakus) [inline lib/vulcan.js]: `isExcludedHref`
